name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1"

    - name: Swift version
      run: swift --version
  
    - name: Build
      run: swift build
  
    - name: Run tests
      run: |
        if [ -d Tests ]; then
          swift test --parallel
        fi